
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'demo' do

    pod 'KLine', :path => '../'
    pod 'Charts', :git => 'https://github.com/pikacode/Charts.git', :branch => 'kline', :commit => 'cb0382c751d80f48a0be56aba08bfefbf749beba'

 
end
 
