
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'demo' do

    pod 'KLine', :path => '../'
    pod 'Charts', :git => 'https://github.com/pikacode/Charts.git', :branch => 'kline', :commit => '66546404a6739173b8e436ab6bc1f2897cd08594'

 
end
 
