
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'demo' do

    pod 'KLine', :path => '../'
    pod 'Charts', :git => 'https://github.com/pikacode/Charts.git', :branch => 'kline', :commit => '6aba70ba95e3bff1941e43677923d057799ca22c'

 
end
 
